### PR TITLE
Slate style menu nsw dds styles

### PR DESCRIPTION
**Pull request by JeffersonBledsoe**
This PR introduces two buttons to the slate toolbar: 'Intro' and 'Small' text sizing. They apply the `nsw-intro` and `nsw-small` text sizes respectively.

https://github.com/pretagov/nsw-design-system-plone6/assets/30210785/c67a780e-89d5-4092-8466-fab92cf85b8d

- [x] add styles menu
- [x] add small and intro as paragraph styles
  - There is a bug causing 'paragraph' styles to still be used as inline styles
- [x] change the icon of format since it makes more sense
- [x] create bug tickets
  - See https://github.com/plone/volto/issues/5422

Currently out of scope is the additional heading styles and the definition list in https://digitalnsw.github.io/nsw-design-system/core/typography/index.html
- we could add in h3-h5 as headings and ignore the ability to set heading as only style for now? or is that not easy?

### CODE REVIEW

**Comment by JeffersonBledsoe** [comment]
@djay Volto out the box provides a way of applying styles to elements, however, it has the following issues.

- It doesn't display in the dropdown menu (shown below) whether a style is applied or not
- It doesn't have an _exclusive mode_, i.e. there's no way to prevent having the `nsw-small` and `nsw-intro` styles applied.
- It groups them all in a single dropdown, with no easy way of grouping this dropdown, changing it's icon or styling the dropdown.

Screenshot 2023-11-19 at 11 24 42 pm

**Comment by djay** [comment]
@JeffersonBledsoe The bugs you point out can all be lived with and raised in volto. 
However, I don't understand why we have 2 text style buttons as well as a dropdown? We only need the dropdown from a single button.

**Comment by JeffersonBledsoe** [comment]
@djay There's no dropdown, it's only the two buttons. The dropdown screenshot was me showing the 'inline styles' functionality built into volto. See the included video for the bar without the dropdown

**Comment by djay** [comment]
@JeffersonBledsoe use the inline styles functionality and not the buttons. The icons for the buttons are not obvious enough so the dropdown is better. But I still don't know what the icon from the dropdown is

**Comment by djay** [comment]
@JeffersonBledsoe icon not changed and they are currently implemented as char styles not paragraph styles as discussed.

**Comment by djay** [comment]
@JeffersonBledsoe if this is done and on UAT then it should not be in QA anymore right?

**Pull request merged**
